name: .NET CI/CD Workflow (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Specify the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore --runtime win-x64

    - name: Run tests
      run: dotnet test --no-restore
      
    - name: Publish project
      run: dotnet publish DSDD.RankingExample --configuration Release --output ./publish --self-contained

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DSDD.RankingExample.zip
        path: ./publish/*
